### PR TITLE
Maps in maps

### LINKED ISSUE #148: Map key syntax highlighting issues
Possibly related to #146 

When you have maps inside maps, all the keys bar the first are incorrectly highlighted. In this example, they take the highlighting of the valid colours.

The code:
```sass
$custom-palettes: (
    alr: (
        alr-blue: (
            x-light: rgb(240, 243, 246),
            light: rgb(144, 165, 187),
            mid-light: rgb(88, 122, 152),
            base: rgb(1, 51, 102),
            dark: rgb(11, 25, 41),
        ),
        alr-orange: (
            base: rgb(218, 125, 0),
            dark: rgb(191, 108, 0),
            x-dark: rgb(125, 73, 5),
        ),
        alr-green: (
            base: rgb(169, 176, 36),
            dark: rgb(103, 106, 55),
        ),
        alr-grey: (
            xx-light: rgb(222, 222, 222),
            x-light: rgb(200, 200, 200),
            light: rgb(68, 68, 68),
            base: rgb(38, 38, 38),
            dark: rgb(17, 17, 17),
        ),
        alr-white: (
            base: rgb(255, 255, 255),
        ),
        alr-black: (
            base: rgb(0, 0, 0),
        ),
    ),
);
```

The issue:

screen shot 2016-07-07 at 12 21 17

### PR DESCRIPTION
**Pull request by esdoppio**
Fixes #148 

Please merge this after #147 😉

### CODE REVIEW

**Comment by 50Wliu** [comment]
Can you rebase this on master @esdoppio?  The commits from #147 are being included in this which makes the diff look really weird.

**Comment by esdoppio** [comment]
Done. 😊  I assumed the PR would be automatically updated once #147 is merged, to reflect the changes in master—only the last two commit remained in this PR since the previous commits are already in master. Is it possible to make the PR automatically update itself?

File: spec/scss-spec.coffee [hunk 1]
```diff
@@ -459,6 +459,21 @@ describe 'SCSS grammar', ->
...
+            alr-blue: (
+              x-light: rgb(240, 243, 246)
+            )
+          )
+        );
+      '''
+
+      expect(tokens[1][1]).toEqual value: 'alr', scopes: ['source.css.scss', 'meta.set.variable.scss', 'meta.set.variable.map.scss', 'support.type.map.key.scss']
+      expect(tokens[2][1]).toEqual value: 'alr-blue', scopes: ['source.css.scss', 'meta.set.variable.scss', 'meta.set.variable.map.scss', 'meta.set.variable.map.scss', 'support.type.map.key.scss']
+      expect(tokens[3][1]).toEqual value: 'x-light', scopes: [ 'source.css.scss', 'meta.set.variable.scss', 'meta.set.variable.map.scss', 'meta.set.variable.map.scss', 'meta.set.variable.map.scss', 'support.type.map.key.scss']
```
Comment (50Wliu) [inline spec/scss-spec.coffee]: You have an extra space after the bracket here.
